sudo: false
# cache:
    # apt: true
    # directories:
    # - $HOME/.cache/pip
    # - $HOME/miniconda
    # - $HOME/download

language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  
env:
  global:
    - FVS_STATUS=alpha
    - BUILD_ROOT=${TRAVIS_BUILD_DIR}/bin/build
    # - FVS_VARIANTS="pnc;wcc"
    - FVS_VARIANTS="pnc;wcc;soc;cac;ecc;oc;op"
    
    # travis encrypt TWINE_USERNAME=<plain text> -r tharen/PyFVS
    - secure: "rPyi4rdjd59a1JwwpLDy4dH7be2wcKB+DA/Zu4dX2BQ4RDSrx0u0V7EsdzKFVrrjzhTjh/+OomaBaJ9uz7xu6HquXVbYqTCVuw+TazAD3u9DLwDwL4FQa+20iCvBE7r5en3XVslCIcpUdkTXD2WNogNl7d+L5P50pdHTSMLDY7DLq0aan4nOHnjOPjXOIcu1Zc1OKyMT5hyi+FWkpyEhkJdZmFkHZcX4R2Ta0Hvk/302H6/FQ+mZtAA4Qb/Yh3dWdv58C1KxGxp2CbOiyxU6P5w2YZX5TgaX6/Wia8opbmlhvEoxMzLiteMHPLSOMLRkNLSsywIcY9Ndunwe/JtbZ74ZmOn+DF0k4BSKCe4P6jIgFbA54+M8Ju/2ZUX4EIxr/MwIbE3BefoWFc+m/ztKXp4K8kAeaHZ0uWqTl7cRRPUtGJrdVjMtFAZF59txBC9famccA4l4ZNBXBmgOep3+UOja+CRsnVNgIwznMOcgTDX5qPO6VKh0UYIiiWUwC40L9uRA4tnVw/bzIiqF2R4vfqiHwiBcOMHL04ipm4SmZDvcN0kTgfFiIdrCZB85WEyQW3xL9kzwiUsiN9rTj+rGQITJZkOVMm00VyovE7dY/pyS9R0/2l4W47I/O5LSKK4mxZG8wqlUvloYUIQhfK19WsYJQZXbSqai03iQCtI9iM8="
    # travis encrypt TWINE_PASSWORD=<plain text> -r tharen/PyFVS
    - secure: "CyiXYT8z3lqZ9sE4gkW+tkXnmNhLJ1hUXJKRw5+K8V/7C1t1XVRBYGsxo0a/2iZ7FpkEpcB7YVuTfOPM8xGxPdvze5EFvGBczKWOEXnDuJKQ90qScDeQ+gNjAI/o8zIdCckT+TIJW9quAaAu4Ry7+bRNeBu+Lf1DVvDWweWlzRuwvMi3yTUyC9soALi2hCp1hJDUdEdtOz3z6wury58+vfqo+kFXHPJ9cWlnFfpaKzeh9nhYk2TiWOZoXsAkGANI3/4M+7ydr3kVZ3iqRqQpzqIo1Cym1P+PX2G3gkMBNj9ukJQsWzxFFho8qiCIm6KaA4qu1ZeuN5z817Gkc7wV/jHBeT/5nYBrI1xclpCE36bSfQjqmKpxr4XywcCqjvfa3fcQIsLOrOCbzD9aqE1TFPSTVEcQKgNAwkpiJ3xqdIYLLKGfqeYewTGzBNDvY/uxjAVtA/OEVjg7hjFcQhiHuXUFyQsASkfQnOUbSsEmtkrJAmRgs3NKHtqfdGMk+C56119d3oeTgpCX9QcHXXS3aMnItJ2+x4UuIXILDsE2xb3r+EpEcvVbUMRhfDMRjnLrajia/nNKmGmrcWba0bgGquYm106aS3JYXnedIq27LeCtrs58M3vDay0pVVTphuOOEsEcgyU07negQ918dY/zab9Q9uAaZT2U1Ib3nfG/dQE="
    
    - MPLBACKEND="agg"

git:
  depth: 5
  
addons:
  apt:
    sources:
    - george-edison55-precise-backports

    packages:
    - cmake
    - cmake-data
    - gfortran
    - unixodbc
    - unixodbc-dev
    - p7zip-full

before_install:
  # Setup the conda environment
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source ${TRAVIS_BUILD_DIR}/.travis-ci/install_miniconda.sh
  - source ${TRAVIS_BUILD_DIR}/.travis-ci/setup_conda.sh
  
install:
  - source activate pyfvs
  - python -c "import sys;print('{}.{}'.format(*sys.version_info[:2]))"
  # Define the name to be used for the archive of compiled products.
  - export ARCHIVE_NAME=pyfvs-${TRAVIS_TAG}-Python${TRAVIS_PYTHON_VERSION}_64-${TRAVIS_OS_NAME}

script:
  # build.sh compiles the Open-FVS binaries and builds the Python wheel and archive
  # Run tests after a successful build, otherwise bail.
  - source ${TRAVIS_BUILD_DIR}/.travis-ci/build.sh
  - pip install --no-index --find-links ${TRAVIS_BUILD_DIR}/artifacts pyfvs
  - pytest -rsx --pyargs pyfvs.test
  - pytest ${TRAVIS_BUILD_DIR}/python/pyfvs/examples/demo.py
  - pytest ${TRAVIS_BUILD_DIR}/python/pyfvs/examples/pn_test.py

after_failure:
  # Push error logs to the console output
  - "cat ${BUILD_ROOT}/build_err.log"
  - "cat ${BUILD_ROOT}/f2py_pnc.log"

after_success:
  # Deploy here to run in the build environment
  # PYPI doesn't accept compiled wheels for Linux.
  # - conda install twine
  # - chmod +x ${TRAVIS_BUILD_DIR}/.travis-ci/deploy_pypi.sh
  # - ${TRAVIS_BUILD_DIR}/.travis-ci/deploy_pypi.sh

deploy:
  # GitHub Releases
  - provider: releases
    skip_cleanup: true
    prerelease: true
    api_key:
      secure: DIF7bPl0y55Q8F8Go0CY40FxN8icu54d2MWRmiuLlGfkeIzcDHHHdJ8W8ZqX/9qyPruWMX/8HvagdKzcLTFC0namicronzZL5XUloR/PGBCT9tRqL3xax36fIHvrmZYIaY7xWIr678s+dG+64lkX5i+BJnt1IDzHjGm+223k3PH/kXRH3NFauPu4PgUszTnIWa+0IBnOhXrodf1A0ljFrtypUleASS19A3PuglHQJRXlDfOpt++M2UHXNBVbhr83jMg8O3XB+BY1QT8g3fYs1kUKmUbxEF6Ab9A/qZtcxIvqK9c55q7sjnaRqvlS5TtQ9ADE1Y97y3hmGNE+xL+x4QCwSC10BGIWvcuVC8Gol/WJY6/EPskNMjKhk9xqhOhqdBiDdyPnLSjhA1zA7e/2mGYwBBw8h9/lvsKvbjHMD47uuKCeDovnB07rYqk6A1bQx4JWAHFwoZB1SuWFT2OcI9aqLE9I/GhiREJgX8I5adJiiqdfLCifSHQINoWUa3b3ZuspFzC+yXIDOwsma5xr7dfMkf+htqofwnzq2R/wM59ryEayfCtdz1VOfrxEnJJfWnL/u9LRbNhGVSP2PBsp59ZIvE5JW3UT12G+bIh9a+veNaExzcoIQYPfb+VJlytvDA21TC/4Ju2gFNwcxeVWm6etkTSUfvsMMYGsUc6+wPY=
    overwrite: true
    file_glob: true
    file: "${TRAVIS_BUILD_DIR}/artifacts/*.whl"
    on:
      repo: tharen/PyFVS
      tags: true

  # Amazon S3 Storage
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAIDXNPYH254RADH4A
    secret_access_key:
      secure: lmFYrGZSd7JpeNCRV0BU0t9ipav/Dg1JK3PX94Wz8y03ymlrGaVjvdUyokdf+fXwFeWb+B4aulU1bI2EW4vv6+U4rm0TPsIHf6myyhXftoKxLydhKDi2H4TRSaaJt6dNABSM156stqYFPSD/TtIZfCa63qZjfkK+RlNGe1WdJ16nhd57M9B/TO0A7Nq6X3TvaVKuL0yGTi8L8cfD3aumbk3ReoD/1bXjYReAteKc5lrWmyxHRyPZyrE2xhrtjTBm88GdXv/LFkeopTC2y2eLD1h2cTCOurBw1RFlxvXBshnLULDlrNkzTCGF6O5aCx7icfXCuNAcgZidYSutziXyWt69NYxlwD/Elqh0coKxnrDaMp/dj84P89DLqA+MyhcXlw2Kf2npLtLgpW1wpBXIGWDRAv1GtJHd+IjabE5htdVz6nhlONsCI/rdHN33rTvgnwiQn3Ypg9dp7vt1JFVYFImdWrflR5CH/sAJAH30FKgerVaHOHty52O/8KXkYggxzCJIOVXb7nmgJSgk/EgGeoI0t8oieudXp/J20+uTAKm3lDwtOCpoVHbi0YSWJgP8Z5KoSMq5AVWubFYxclUwDd/xwjhhN1wZ/YVQIZ4xG8dP33+ZkodZ46AX0u+IwI2REsV0t03nG0FtwXWETcCb8SWvdqGqJCHNEcHeL/yG28A=
    region: us-west-2
    bucket: free5
    local-dir: ${TRAVIS_BUILD_DIR}/artifacts
    upload-dir: pyfvs/$TRAVIS_BRANCH
    acl: public_read
    on:
      repo: tharen/PyFVS
      all_branches: true
