version: '0.0.13-{build}'
environment:
  global:
    MPLBACKEND: agg
    MINGW_PATH: 'C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64'
    FVS_VARIANTS: pnc;wcc;soc;cac;ecc;oc;op
    TWINE_PASSWORD:
      secure: lLhgSTVGnQNINPD18gIe2g==
    TWINE_USERNAME:
      secure: 8hDc5xW8gYDuUGz/TNWNoA==
  matrix:
    -
      MINICONDA: 'C:\Miniconda3-x64'
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
    -
      MINICONDA: 'C:\Miniconda3-x64'
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '64'
    -
      MINICONDA: 'C:\Miniconda3-x64'
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
    -
      MINICONDA: 'C:\Miniconda3-x64'
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
    -
      MINICONDA: 'C:\Miniconda3-x64'
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
init:
  - 'echo PYTHON_VERSION %PYTHON_VERSION%'
  - 'echo MINICONDA %MINICONDA%'
install:
  - 'set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%'
  - 'set PATH=%MINGW_PATH%\bin;%PATH%'
  - 'call %APPVEYOR_BUILD_FOLDER%\\.appveyor\\setup_conda.bat'
  - 'call activate pyfvs'
build_script:
  - 'call %APPVEYOR_BUILD_FOLDER%\\.appveyor\\config_and_build.bat'
after_build:
  - '%APPVEYOR_BUILD_FOLDER%\.appveyor\bundle_archive.bat'
test_script:
  - 'call "%APPVEYOR_BUILD_FOLDER%\\.appveyor\\run_tests.bat"'
on_success:
  - 'call %APPVEYOR_BUILD_FOLDER%\\.appveyor\\deploy_pypi.bat'
on_failure:
  - 'appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\\bin\\build\\build_err.log'
  - 'appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\\bin\\build\\pypnc_f2py.log'
artifacts:
  -
    path: 'pyfvs*.zip'
    name: pyfvs-zip
    type: zip
  -
    path: 'pyfvs*.whl'
    name: pyfvs-wheel
    type: whl
deploy:
  -
    provider: GitHub
    description: 'Appveyor CI tag build.'
    auth_token:
      secure: Pi+Rn4LnPIHYZJ6uMQa4im0nQvZ6YMoBsGiGwzEpe1ZcJsunZ9D/snlNfjLlvA2w
    artifact: pyfvs-wheel
    draft: true
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true
  -
    provider: S3
    access_key_id: AKIAIVJ4GCLXEX2KK5QQ
    secret_access_key:
      secure: 3i/lHf5+t5tHVnX5dM/iHO9vOuvEZk65jCR94F1QSObHs8X5D1ZkY+BLW4fetlLC
    region: us-west-2
    bucket: free5
    set_public: true
    folder: pyfvs/%APPVEYOR_REPO_BRANCH%
    artifact: 'pyfvs-zip pyfvs-wheel'
